[package]
name = "malaphor-rust"
version = "0.1.0"
authors = ["Martti Soininen <martti.soininen@evident.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"